### ISSUE TITLE
No dygraph or highcharter support?

### ISSUE THREAD

**Issue by georgemirandajr** [kylebutts/tailwindr#1]
First, thanks so much for an awesome package.  I love tailwind and this makes it so easy to use within R.  The issue I'm noticing is using htmlwidgets with this package.  I'm using dygraphs and highcharter inside the rmarkdown and those are not rendering at all.  Ggplot2 images render fine though.    I used the template provided using 
`output: 
  tailwindr::tailwind_prose:
    highlight: zenburn
    self_contained: false
    slim_css: TRUE
    css: []`

The chart I tried plotting was a simple example from highcharter's [webpage](https://jkunst.com/highcharter/articles/hchart.html#time-series)
`library(highcharter)
hchart(cor(mtcars))
`

![image](https://user-images.githubusercontent.com/6701264/165639235-79c89bdb-10a4-4111-a62b-2b89f6d0dea4.png)

The version of highcharter I'm using is 0.8.2 in R Studio Version 1.3.1073 with the following R info
`platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night      `

I tried inspecting the code in the browser but I don't see anything obviously wrong.  The js code produced by highcharter appears to be linking correctly to the div container.  Any ideas?

**Comment by kylebutts** [comment]
Hi George, I've been on a conference so that's why I haven't been able to look at this yet. I'll reply to this when I'm back and can dig into it a bit more. In the meanwhile, I think you can use the following yaml:

```yaml
---
title: "Habits"
output:
  html_document:
    theme: null
---
```

This will remove the bootstrap themes. Then include `<script src="https://cdn.tailwindcss.com"></script>` to include the tailwind play CDN. More details here: https://tailwindcss.com/docs/installation/play-cdn

**Comment by kylebutts** [comment]
Hi @georgemirandajr,

Here's a full example of what I described above! It works well and will be much easier to maintain, though admittedly less "clean" of code than using the tailwind_prose template

https://gist.github.com/kylebutts/95c4eb9be431900ad12b11f302b02211

**Comment by georgemirandajr** [comment]
That worked like a charm!  Great solution.
